package:
  name: febio
  version: "0.1.3"

source:
  fn: febio-0.1.3.tar.gz
  url: https://files.pythonhosted.org/packages/90/7a/64618af15752345a1d5a6a2cbdf87b3f18fb87c123ab98c0677681f73730/febio-0.1.3.tar.gz
  md5: 889f1140b2eb33cb829eafff49b7c5c0
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - febio = febio:main
    #
    # Would create an entry point called febio that calls febio.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - febio

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/siboles/pyFEBio
  license: MIT
  summary: 'A Python API for FEBio'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
