package:
  name: febio
  version: "0.1"

source:
  fn: febio-0.1.tar.gz
  url: https://files.pythonhosted.org/packages/ba/4e/9c242acc588aab465df03ea7794485d401566ef6d76e1ce435f89ab73156/febio-0.1.tar.gz
  md5: b9737f467808477051454dd211ea01a9
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - febio = febio:main
    #
    # Would create an entry point called febio that calls febio.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy
    - h5py
  run:
    - python
    - numpy
    - h5py

test:
  # Python imports
  imports:
    - febio

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https:/github.com/siboles/pyFEBio
  license: MIT
  summary: 'A Python API for FEBio'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
